name: gradle CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Dependencies (Windows)
        run: |
          choco install winflexbison
          ren "C:\ProgramData\chocolatey\bin\win_bison.exe" "bison.exe"
          ren "C:\ProgramData\chocolatey\bin\win_flex.exe" "flex.exe"

      - name: Fetch Dependencies
        run: gradle --init-script gradle/support/fetchDependencies.gradle init

      - name: Build with Gradle
        run: gradle buildGhidra

      - uses: actions/upload-artifact@v3
        with:
          name: Releases
          path: build/dist/
